services:
  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - frontend_data:/app/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "3001"
    env_file:
      - .env
    volumes:
      - backend_data:/app/data

  vdr:
    build:
      context: ./vdr
      dockerfile: Dockerfile
    expose:
      - "3002"
    env_file:
      - .env
    volumes:
      - vdr_data:/app/data

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
      - vdr

volumes:
  frontend_data:
  backend_data:
  vdr_data:
  caddy_data:
  caddy_config:
